function library = complexityLibrary()
%COMPLEXITYLIBRARY Library of real-life driving complexity events.
% Each entry is one behavior module that can be attached to an actor
% while generating a scenario.
%
% Fields:
%   name        - unique identifier of the event
%   actorType   - 'car','truck','bus','bicycle','pedestrian','child'
%   roadTypes   - cell array of road types this event fits on
%                 {'highway','rural','village'}
%   label       - 0 = SAFE behavior, 1 = RISKY behavior  (ground truth)
%   description - human readable description

library = struct('name',{}, 'actorType',{}, 'roadTypes',{}, 'label',{}, 'description',{});

library(end+1) = struct('name','aggressive_lane_change', 'actorType','car', ...
    'roadTypes',{{'highway'}}, 'label',1, ...
    'description','Vehicle changes lanes abruptly at high speed without signaling.');

library(end+1) = struct('name','sudden_braking', 'actorType','car', ...
    'roadTypes',{{'highway','rural'}}, 'label',1, ...
    'description','Lead vehicle brakes hard unexpectedly.');

library(end+1) = struct('name','tailgating', 'actorType','car', ...
    'roadTypes',{{'highway','rural'}}, 'label',1, ...
    'description','Vehicle follows the vehicle ahead at an unsafe close distance.');

library(end+1) = struct('name','unsafe_overtake', 'actorType','car', ...
    'roadTypes',{{'rural'}}, 'label',1, ...
    'description','Vehicle overtakes on a two-lane rural road with oncoming traffic.');

library(end+1) = struct('name','speeding_zigzag', 'actorType','bicycle', ...
    'roadTypes',{{'village','rural'}}, 'label',1, ...
    'description','Cyclist swerves unpredictably across the lane.');

library(end+1) = struct('name','child_chasing_ball', 'actorType','child', ...
    'roadTypes',{{'village'}}, 'label',1, ...
    'description','A child suddenly runs into the road while chasing a ball.');

library(end+1) = struct('name','jaywalking_pedestrian', 'actorType','pedestrian', ...
    'roadTypes',{{'village','rural'}}, 'label',1, ...
    'description','Pedestrian crosses mid-block, outside the marked crossing.');

library(end+1) = struct('name','bus_sudden_stop', 'actorType','bus', ...
    'roadTypes',{{'village','rural'}}, 'label',1, ...
    'description','Bus stops abruptly at an unmarked stop to pick up passengers.');

library(end+1) = struct('name','truck_merging', 'actorType','truck', ...
    'roadTypes',{{'highway'}}, 'label',1, ...
    'description','Truck merges into traffic without an adequate gap.');

library(end+1) = struct('name','animal_or_obstacle_crossing', 'actorType','pedestrian', ...
    'roadTypes',{{'rural'}}, 'label',1, ...
    'description','Unexpected obstacle/animal crosses a rural road (modeled as an actor).');

library(end+1) = struct('name','safe_lane_change', 'actorType','car', ...
    'roadTypes',{{'highway'}}, 'label',0, ...
    'description','Vehicle signals and changes lanes smoothly.');

library(end+1) = struct('name','safe_following', 'actorType','car', ...
    'roadTypes',{{'highway','rural'}}, 'label',0, ...
    'description','Vehicle maintains a safe following distance.');

library(end+1) = struct('name','safe_crosswalk_pedestrian', 'actorType','pedestrian', ...
    'roadTypes',{{'village'}}, 'label',0, ...
    'description','Pedestrian waits and crosses only at the marked crosswalk.');

library(end+1) = struct('name','safe_cyclist', 'actorType','bicycle', ...
    'roadTypes',{{'village','rural'}}, 'label',0, ...
    'description','Cyclist rides steadily within the bike lane.');

library(end+1) = struct('name','safe_bus_stop', 'actorType','bus', ...
    'roadTypes',{{'village','rural'}}, 'label',0, ...
    'description','Bus signals in advance and stops smoothly at a marked bus stop.');

% --- Intersection (crossroad) events ---
library(end+1) = struct('name','running_red_light', 'actorType','car', ...
    'roadTypes',{{'crossroad'}}, 'label',1, ...
    'description','Vehicle enters the intersection against a red signal.');

library(end+1) = struct('name','failure_to_yield', 'actorType','car', ...
    'roadTypes',{{'crossroad'}}, 'label',1, ...
    'description','Vehicle turns left across traffic without yielding to oncoming vehicles.');

library(end+1) = struct('name','safe_intersection_stop', 'actorType','car', ...
    'roadTypes',{{'crossroad'}}, 'label',0, ...
    'description','Vehicle comes to a complete stop and yields correctly before proceeding.');

library(end+1) = struct('name','pedestrian_jaywalk_intersection', 'actorType','pedestrian', ...
    'roadTypes',{{'crossroad'}}, 'label',1, ...
    'description','Pedestrian crosses the intersection against the signal.');

library(end+1) = struct('name','safe_pedestrian_crosswalk_intersection', 'actorType','pedestrian', ...
    'roadTypes',{{'crossroad'}}, 'label',0, ...
    'description','Pedestrian waits for the signal and crosses within the marked crosswalk.');

% --- Railway level-crossing events ---
library(end+1) = struct('name','railway_dash_crossing', 'actorType','car', ...
    'roadTypes',{{'rail_crossing'}}, 'label',1, ...
    'description','Vehicle speeds across the level crossing as the train approaches, ignoring the barrier/warning.');

library(end+1) = struct('name','safe_railway_wait', 'actorType','car', ...
    'roadTypes',{{'rail_crossing'}}, 'label',0, ...
    'description','Vehicle stops safely behind the barrier and waits for the train to pass.');

library(end+1) = struct('name','pedestrian_railway_dash', 'actorType','pedestrian', ...
    'roadTypes',{{'rail_crossing'}}, 'label',1, ...
    'description','Pedestrian ducks under the barrier to cross just before the train arrives.');

end